export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_COUNTER2 = 'INCREMENT_COUNTER2';
export const DECREMENT_COUNTER2 = 'DECREMENT_COUNTER2';
